### ISSUE TITLE
FR: create classic style sound resource addon

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/skin.titan#198]
http://forum.kodi.tv/showthread.php?tid=234547&pid=2270071#pid2270071

**Comment by mgonzales71** [comment]
Here you go Marcel,

https://onedrive.live.com/redir.aspx?cid=599da6bd82779e65&resid=599DA6BD82779E65!6304&parId=599DA6BD82779E65!4605&authkey=!AJtTSaLhVDn5PVs&ithint=file%2czip

I didn't include any new sounds (the additional types used in the modern like vol up, down, etc) - just the original classic sounds and types.  If you want I can re-do with those included with the old/classic ones.

I can do a pull request later if you like - just wasn't sure what branch you wanted me to target... Isengard or have you moved to Master?

also made a new icon in the style of the modern one.  (included in zip/addon)

![icon](https://cloud.githubusercontent.com/assets/6510026/13561024/3b9f416e-e3dc-11e5-8224-954473e0640d.png)

**Comment by mgonzales71** [comment]
Created a PR - https://github.com/marcelveldt/skin.titan/pull/200

after I got back home - thought about it again and it made sense to target Isengard since you are merging changes that are compatible like this upstream.

let me know if you need any changes, etc.

as always glad to help :smile:

Mario

**Comment by marcelveldt** [comment]
thanks Mario!!
