### ISSUE TITLE
many problems with menus and shortcuts with Titan 3,6,59

### ISSUE THREAD

**Issue by switchtv** [marcelveldt/skin.titan#217]
I am new to Kodi
Love the titan skin,,,do not wish to change
Titan ver 3.6.59
Jarvis ver Kodi
Win 10 Os

My issues, 

lost all but 6 menu items, although 9 configured
tried to reset skin properties no help

Uninstalled Titan, reinstalled,,,menus got re written upon start up,,limited to 6

Uninstalled Kodi,,,using Reno

Fresh install of Kodi

fresh install of Titan,,,,,menus still re written,,,but then had 7 menus,,,,and no sub menus

BACK BUTTON AND HOME SCREEN BUTTON,,also have vanished

Had a BU of my entire Kodi,,,on another win 10 unit

Deleted is,,,,reinstalled Titan

Same result,,,only back to only 6 menus,,,and no sub menus

each time i make a menu change on either unit,,,i loose one menu shortcut,,,now at 4 after deleteing 1,,,and adding 2

i am lost

i also deleted all menus,,,,and recreated 8,,,and only 6 show

I do believe these problems started,,,when i upgrade to Jarvis Kodi

I had  Helix,,,,and do believe all were working fine

how can i stop the re writing of the menus and shortcuts,,and start a fresh install ,,i just love this skin,,,excellent work,,,and would so love to have Titan back

R

**Comment by mgonzales71** [comment]
I think you may want to post at http://forum.kodi.tv/forumdisplay.php?fid=212
lots more help and info there.

If you want todo a clean re-install I suggest the following:

NOTE - example paths below - your username will be different

first If you can - try to do a back up of your skin settings in Kodi

Look under:
Skin Setting - Backup and Restore

better yet backup the entire C:\Users\Mario\AppData\Roaming\Kodi\userdata\ directory just to be safe

Summary of clean install of Titan and it's main supporting addons and settings.

Remove the skin, skin shortcuts, the helper script and settings...

**Tian Skin:**
C:\Users\Mario\AppData\Roaming\Kodi\addons\skin.titan.jarvisbeta
C:\Users\Mario\AppData\Roaming\Kodi\addons\skin.titan  
etc

**Titan skin's settings:**
C:\Users\Mario\AppData\Roaming\Kodi\userdata\addon_data\skin.titan.jarvisbeta
C:\Users\Mario\AppData\Roaming\Kodi\userdata\addon_data\skin.titan
etc

** under skin settings - backup and restore you can also reset skin settings to default

**Skin Shortcuts**
(this is what builds the menu's for Titan and other skins)
addon: C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skinshortcuts
settings: C:\Users\Mario\AppData\Roaming\Kodi\userdata\addon_data\script.skinshortcuts

**Skin Helper Script**
addon:  C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service
settings: C:\Users\Mario\AppData\Roaming\Kodi\userdata\addon_data\script.skin.helper.service

once you have deleted (or moved) the above addon and settings

Start Kodi and re-install the skin from the repo.  Kodi should startup in the confluence (default skin) unless you are using a Krypton nightly.

Installing the skin will re-install skin shortcuts and the skin helper script since they are required.

hope that helps.

issues with skin.shortcuts happen sometimes.  It sounds to me like something crashed during a skin shortcut rebuild or skin or skin helper update/install and settings were corrupted.

I recommend you do frequent backups via the skin, your own software or the programm addon called Kodi Backup.

backup of C:\Users\Mario\AppData\Roaming\Kodi\* is best but you can omit the addons dir to reduce backup size - you will just have to re-install all addons if you need to do a restore,

I backup daily and after any major skin settings changes.

Cheers

Mario

**Comment by marcelveldt** [comment]
please use the kodi forums for support.
