### ISSUE TITLE
FR: add squared homemenu options

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/skin.titan#220]
- vertical squared menu items
- horizontal squared menu items

http://forum.kodi.tv/showthread.php?tid=205482&pid=2356510#pid2356510

**Comment by mgonzales71** [comment]
I like this idea!!


Slightly related to this - since square menu items would best fit with skin icons included in skin image resource addons...
 
maybe you could incorporate the selection or use of artwork / icons from installed skin resource packs?

resource.images.skinicons.*
resource.images.skinbackgrounds.*

Like a list item / selection called "use matching skin icon / background"?

for instance - one of the skin backgrounds addons has images for the following menu items:

resources\addons.jpg
resources\dvd.jpg
resources\favorites.jpg
resources\filemanager.jpg
resources\kids.jpg
resources\livetv.jpg
resources\movies.jpg
resources\music.jpg
resources\musicvideos.jpg
resources\pictures.jpg
resources\power.jpg
resources\radio.jpg
resources\search.jpg
resources\setings.jpg
resources\software.jpg
resources\sport.jpg
resources\tvshows.jpg
resources\video.jpg
resources\vod.jpg
resources\weather.jpg

but I do like the idea of having square tiles at the very least :+1:

**Comment by FIREEYESa1** [comment]
I am glad someone brought up the square icons for main menu items; this
would be great.  I already use the icons in the Kodi repo for widget icons,
submenu, various addons and Kodi functions.  I also use addons for my main
menu.  I tried using vertical tiles but distorted the icons to much.
Thank for taking the time to listen and respond to the input of Titan
fans.  Your efforts to make this skin the best are obvious.

On Wed, Jun 29, 2016 at 6:07 AM Mario <notifications@github.com> wrote:

> I like this idea!!
>
> Slightly related to this - since square menu items would best fit with
> skin icons included in skin image resource addons...
>
> maybe you could incorporate the selection or use of artwork / icons from
> installed skin resource packs?
>
> resource.images.skinicons.*
> resource.images.skinbackgrounds.*
>
> Like a list item / selection called "use matching skin icon / background"?
>
> for instance - one of the skin backgrounds addons has images for the
> following menu items:
>
> resources\addons.jpg
> resources\dvd.jpg
> resources\favorites.jpg
> resources\filemanager.jpg
> resources\kids.jpg
> resources\livetv.jpg
> resources\movies.jpg
> resources\music.jpg
> resources\musicvideos.jpg
> resources\pictures.jpg
> resources\power.jpg
> resources\radio.jpg
> resources\search.jpg
> resources\setings.jpg
> resources\software.jpg
> resources\sport.jpg
> resources\tvshows.jpg
> resources\video.jpg
> resources\vod.jpg
> resources\weather.jpg
>
> but I do like the idea of having square tiles at the very least 👍
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/marcelveldt/skin.titan/issues/220#issuecomment-229350047>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALJBFN0lVatWoF3HKgOqkXG-gjtAz01hks5qQm4WgaJpZM4JAkwn>
> .
>
-- 
James E.Harris
