### ISSUE TITLE
FR: add movie title of current rotating random fanart

### ISSUE THREAD

**Issue by marcelveldt** [marcelveldt/skin.titan#42]
option in skin to display the current displayed fanart picture's title somewhere..

http://forum.kodi.tv/showthread.php?tid=201061&pid=1982330#pid1982330

**Comment by mgonzales71** [comment]
hmmm - 

sorry to jump in - but got my thinking about this after I read it....

my suggestion you even decide to add this as an option...

since you already have the option of "do not display title on home menu tiles"
that you could offer an option in "configure menu shortcuts" with the option to "set custom tile image" for a tile to

tv or movie:

clear art (if available)
landscape (if available)
clear logo (if available)
or
fanart (also could be the fallback image for other options)

Mario

**Comment by mgonzales71** [comment]
actually if you do go with this as a feature....

would you consider updating the widget to display something like this (instead of just text) when landscape artwork is not available but the logo artwork is....  (may want to remove the panel as well possibly?) - even expand it as an option in settings *(new widget category in settings if you get enough features added :smile:)

![2015-05-31_21-50-44](https://cloud.githubusercontent.com/assets/6510026/7906451/586ea8bc-07e0-11e5-8ace-4965faf4c67e.jpg)

**Comment by marcelveldt** [comment]
this is added a few versions back
